const ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

const TOURNAMENT_MODES = {
  SOLO: 'SOLO',
  DUO: 'DUO',
  SQUAD: 'SQUAD',
  CUSTOM: 'CUSTOM'
};

const TOURNAMENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  LIVE: 'LIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_STATUS = {
  INITIATED: 'INITIATED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
};

module.exports = {
  ROLES,
  TOURNAMENT_MODES,
  TOURNAMENT_STATUS,
  PAYMENT_STATUS
};
